# Generated by Django 6.0.1 on 2026-01-10 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.county'),
        ),
        migrations.AddField(
            model_name='county',
            name='county_name_en',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='county',
            name='county_name_ru',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='street_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='street_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_status_en',
            field=models.CharField(choices=[('Занят', 'Занят'), ('Забронирован', 'Забронирован'), ('Свободен', 'Свободен')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_status_ru',
            field=models.CharField(choices=[('Занят', 'Занят'), ('Забронирован', 'Забронирован'), ('Свободен', 'Свободен')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
