# Generated by Django 6.0.1 on 2026-01-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_rename_county_country_alter_hotel_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='county_name',
            new_name='country_name',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='county_name_en',
            new_name='country_name_en',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='county_name_ru',
            new_name='country_name_ru',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='county',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='country',
            name='country_image',
            field=models.ImageField(upload_to='country_images'),
        ),
    ]
