# Generated by Django 6.0.1 on 2026-01-11 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_rename_county_name_country_country_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='ower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
